# -*- coding: utf-8 -*-
"""Tarea2ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYjt_FO_qYPy2A66MJjQBSxa9wVKm__2

# Tarea 2:  Health Landscape – ENO + GRD

- **Integrantes:** Ignacio Corvalán y Valentina Cornejo
- **Profesor:** Leo Ferres
- **Ayudante:** Antuan Vayisqui
- **Región asignada:** Región Metropolitana
- **Comuna asignada:** La Florida
- **Código comuna:** 13110

En esta tarea se construye un panorama de salud de la comuna de La Florida utilizando los datasets ENO y GRD. Además, se reutilizan indicadores demográficos obtenidos en la Tarea 1, especialmente la población total y el porcentaje de población extranjera, para calcular tasas y contextualizar los resultados.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile
import geopandas as gpd

plt.figure(figsize=(8,5))
sns.set_style("whitegrid")
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

"""En esta sección se importan las librerías necesarias para cargar, limpiar, analizar y visualizar los datos."""

MY_COMUNAS = [13110]

t1_summary = pd.DataFrame({
    "codigo_comuna": [13110],
    "nombre_comuna": ["La Florida"],
    "pop_total": [374836],
    "pop_foreign": [36685],
    "pct_foreign": [9.79]
})

t1_summary["codigo_comuna"] = t1_summary["codigo_comuna"].astype(str)
t1_summary["nombre_comuna_upper"] = t1_summary["nombre_comuna"].str.upper()

t1_summary

"""La tabla anterior resume la información demográfica obtenida en la Tarea 1 para la comuna de La Florida. Esta información se utilizará como base para calcular tasas por 10.000 habitantes y para contextualizar la participación de población extranjera en los análisis de ENO y GRD.

## Parte A: ENO – Carga y limpieza de datos

En esta sección se carga la base ENO, se seleccionan solo las variables necesarias y se filtran los registros correspondientes a la comuna de La Florida.
"""

eno_cols = [
    "ENO", "anho_notificacion", "region", "codigo_comuna_residencia",
    "nacionalidad", "sexo", "grupo_edad", "nombre_instruccion",
    "cie_10_diagnostico", "diagnostico", "pais_contagio"
]

eno = pd.read_csv(
    "20241218_base_eno_final.csv",
    sep=";",
    encoding="utf-8-sig",
    usecols=eno_cols
)

print("Shape ENO:", eno.shape)
eno.info()

eno["codigo_comuna_residencia"] = eno["codigo_comuna_residencia"].astype(str)

anon_rows = (eno["codigo_comuna_residencia"] == "*****").sum()
print("Filas anonimizadas en ENO:", anon_rows)

eno_com = eno[eno["codigo_comuna_residencia"].isin(["13110"])].copy()
print("Filas de La Florida:", len(eno_com))

"""Se filtró la base ENO para trabajar únicamente con la comuna de **La Florida** (`13110`). Como resultado, se obtuvieron **2.128 registros** correspondientes a esta comuna."""

nat_dist = eno_com["nacionalidad"].value_counts(dropna=False).reset_index()
nat_dist.columns = ["nacionalidad", "cantidad"]
nat_dist["porcentaje"] = nat_dist["cantidad"] / nat_dist["cantidad"].sum() * 100
nat_dist

eno_nat = eno_com[eno_com["nacionalidad"] != "Desconocido"].copy()

dropped_nat = len(eno_com) - len(eno_nat)
pct_dropped = dropped_nat / len(eno_com) * 100 if len(eno_com) > 0 else 0

print("Filas excluidas por nacionalidad desconocida:", dropped_nat)
print("Porcentaje excluido:", round(pct_dropped, 2), "%")

"""En la comuna de La Florida, la mayoría de las notificaciones ENO corresponde a personas de nacionalidad chilena (**1.539 casos; 72,32%**), seguida por personas extranjeras (**342 casos; 16,07%**). Además, se registran 247 casos con nacionalidad desconocida (**11,61%**).

Para realizar comparaciones por nacionalidad, se excluyeron los registros clasificados como Desconocido, lo que implicó eliminar **247 observaciones**, equivalentes al **11,61%** del total. Esta exclusión permite un análisis más claro entre población chilena y extranjera, aunque reduce parcialmente la cobertura de los datos.

"""

print("Año mínimo:", eno_com["anho_notificacion"].min())
print("Año máximo:", eno_com["anho_notificacion"].max())

eno_year = (
    eno_com.groupby("anho_notificacion")
    .size()
    .reset_index(name="notificaciones")
    .sort_values("anho_notificacion")
)

eno_year

"""La base filtrada para la comuna de La Florida contiene registros desde el año 2007 hasta el año 2024 lo que nos permite tener una amplia visión de datos.

En términos generales, durante los primeros años se observa un volumen relativamente bajo de notificaciones, con cifras que se mueven entre **34 y 101 casos anuales** entre 2007 y 2018. Posteriormente, se aprecia un aumento importante en **2019**, año en que las notificaciones suben a **224 casos**.

Luego, en **2020** y **2021**, los registros vuelven a bajar a **99** y **98 casos**, respectivamente. Más adelante, se observa un nuevo incremento en **2022** (**149 casos**) y, sobre todo, en **2023**, que presenta el valor más alto de toda la serie con **425 notificaciones**. Finalmente, en **2024** se registran **232 casos**, cifra menor a la del año anterior, pero aún superior a la mayoría de los años previos.

Estos resultados muestran que las notificaciones ENO en La Florida no siguen una tendencia completamente estable, sino que presentan variaciones importantes en el tiempo. Estas diferencias pueden reflejar cambios en la situación epidemiológica, en los sistemas de vigilancia o en la intensidad del registro de casos.
"""

plt.figure(figsize=(10,5))
sns.lineplot(data=eno_year, x="anho_notificacion", y="notificaciones", marker="o")
plt.title("Notificaciones ENO por año - La Florida")
plt.xlabel("Año")
plt.ylabel("Cantidad de notificaciones")
plt.xticks(rotation=45)
plt.show()

"""El gráfico de tendencia anual muestra que las notificaciones ENO en La Florida presentan un comportamiento variable a lo largo del tiempo, sin una trayectoria completamente lineal.

Entre **2007 y 2018**, las notificaciones se mantienen en niveles relativamente moderados, con oscilaciones acotadas y una tendencia general al alza, aunque gradual. En **2019** se observa un primer aumento importante, alcanzando **224 notificaciones**, lo que marca un quiebre respecto de los años anteriores.

Posteriormente, en **2020** y **2021**, las notificaciones descienden nuevamente y se estabilizan en torno a los **100 casos**, lo que podría estar influido por cambios en los patrones de vigilancia, acceso al sistema de salud o contexto sanitario general. A partir de **2022** vuelve a observarse un aumento, que se intensifica fuertemente en **2023**, año en que se registra el punto más alto de toda la serie con **425 notificaciones**.

Finalmente, en **2024** se aprecia una disminución respecto de 2023, llegando a **232 casos**, aunque esta cifra sigue siendo elevada en comparación con gran parte del período analizado. En conjunto, el gráfico sugiere que la carga de notificaciones en La Florida ha tendido a incrementarse en los años más recientes, aunque con fluctuaciones importantes entre períodos.
"""

eno_year_nat = (
    eno_nat.groupby(["anho_notificacion", "nacionalidad"])
    .size()
    .reset_index(name="notificaciones")
)

eno_year_nat

plt.figure(figsize=(10,5))
sns.lineplot(
    data=eno_year_nat,
    x="anho_notificacion",
    y="notificaciones",
    hue="nacionalidad",
    marker="o"
)
plt.title("Notificaciones ENO por año y nacionalidad - La Florida")
plt.xlabel("Año")
plt.ylabel("Cantidad de notificaciones")
plt.xticks(rotation=45)
plt.show()

"""El gráfico por nacionalidad muestra que, a lo largo de todo el período analizado, las notificaciones ENO en La Florida son sistemáticamente más altas en la población chilena que en la población extranjera. Esto era esperable, considerando que la población chilena sigue siendo mayoritaria dentro de la comuna.

Sin embargo, también se observa que las notificaciones asociadas a población extranjera aumentan con mayor claridad en los años más recientes. Mientras en los primeros años su presencia es muy baja, a partir de 2016 comienza a apreciarse un crecimiento más visible, que se intensifica entre 2018 y 2024.

En particular, tanto en población chilena como extranjera se observa un aumento importante en 2019, una caída posterior en 2020-2021, y luego un nuevo incremento en 2022 y 2023. El año 2023 concentra el valor más alto para ambos grupos, seguido de una disminución en 2024, aunque manteniéndose por encima de muchos años anteriores.

En términos generales, el gráfico sugiere que la participación de las personas extranjeras en las notificaciones ENO ha ido ganando mayor presencia en el tiempo. Esto resulta coherente con el aumento de la población migrante observado en la comuna y será importante contrastarlo más adelante con el porcentaje de población extranjera obtenido en la Tarea 1.
"""

top10_diseases = eno_com["ENO"].value_counts().head(10).reset_index()
top10_diseases.columns = ["ENO", "cantidad"]

top10_diseases

plt.figure(figsize=(10,6))
sns.barplot(data=top10_diseases, x="cantidad", y="ENO")
plt.title("Top 10 enfermedades notificadas - La Florida")
plt.xlabel("Cantidad")
plt.ylabel("Enfermedad")
plt.show()

"""Lo que hicimos, fue poder ver qué enfermedades padecen con mayor cantidad los habitantes de la comuna de La Florida, al principio lo podemos observar en fortmato de tabla y luego apreciarlo con mejor visual en un gráfico de barras.

Acá, podemos ver las 10 enfermedades más comúnes de los habitantes de la comuna, en donde la enfermedad más común es el **VIH** con más de 1000 personas, siguinedo la **Sifilis** con mas de 200 personas.
"""

pct_foreign_t1 = t1_summary.loc[0, "pct_foreign"]
pct_foreign_t1

top5 = eno_com["ENO"].value_counts().head(5).index.tolist()
top5

eno_top5_nat = eno_nat[eno_nat["ENO"].isin(top5)].copy()

share_top5 = (
    eno_top5_nat.groupby(["ENO", "nacionalidad"])
    .size()
    .reset_index(name="n")
)

share_top5["pct"] = share_top5.groupby("ENO")["n"].transform(lambda x: x / x.sum() * 100)

share_top5

plt.figure(figsize=(10,6))
sns.barplot(data=share_top5, x="ENO", y="pct", hue="nacionalidad")
plt.axhline(pct_foreign_t1, linestyle="--", label="Pct. extranjera Tarea 1")
plt.title("Participación por nacionalidad en top 5 enfermedades - La Florida")
plt.xlabel("Enfermedad")
plt.ylabel("Porcentaje dentro de la enfermedad")
plt.xticks(rotation=45, ha="right")
plt.legend()
plt.show()

"""## Perfil por nacionalidad en las 5 enfermedades más frecuentes

En esta sección se buscó analizar cómo se distribuyen las notificaciones entre población chilena y extranjera dentro de las 5 enfermedades más frecuentes observadas en la comuna de La Florida.

Primero, se recuperó desde la tabla resumen de la Tarea 1 el valor de `pct_foreign`, que corresponde al porcentaje de población extranjera en la comuna. En este caso, dicho valor es **9,79%**. Este porcentaje se utilizó como punto de referencia para evaluar si, en algunas enfermedades, la participación de personas extranjeras es mayor o menor a lo esperable según su peso dentro de la población total.

Luego, se identificaron las cinco enfermedades más notificadas en la base ENO filtrada para La Florida. A partir de ese subconjunto, se trabajó únicamente con los registros que tenían nacionalidad conocida, es decir, Chile o Extranjero, excluyendo previamente los casos clasificados como Desconocido.

Después, se agruparon los datos por enfermedad y nacionalidad, calculando el número de casos en cada combinación. Posteriormente, para cada enfermedad se calculó el porcentaje que representa cada nacionalidad dentro del total de casos de esa enfermedad. De esta manera, fue posible comparar la composición interna de cada diagnóstico y no solo sus cantidades absolutas.

Finalmente, estos resultados se presentaron en una tabla y en un gráfico de barras.

### Resultados obtenidos

Los resultados muestran que, en las cinco enfermedades analizadas, la población **chilena** sigue siendo mayoritaria en todos los casos. Sin embargo, la participación de la población **extranjera** varía bastante según la enfermedad.

En Chagas, las notificaciones corresponden en un **94,84%** a población chilena y solo en un **5,16%** a población extranjera. Algo similar ocurre con Parotiditis, donde la población extranjera representa un **6,09%**, también por debajo del porcentaje comunal de referencia.

En **Infección gonocócica**, la participación extranjera alcanza un **13,21%**, lo que ya se sitúa por encima del **9,79%** observado en la Tarea 1. Esto sugiere una presencia relativamente mayor de población extranjera en esta enfermedad, aunque la diferencia no es tan marcada como en otros casos.

Los resultados más relevantes aparecen en **Sífilis** y **VIH**. En **Sífilis**, la población extranjera concentra un **22,57%** de los casos, mientras que en **VIH** alcanza un **23,03%**.


"""

top_disease = eno_com["ENO"].value_counts().idxmax()
print("Enfermedad más frecuente:", top_disease)

eno_top_age = eno_nat[eno_nat["ENO"] == top_disease].copy()

plt.figure(figsize=(11,6))
sns.countplot(
    data=eno_top_age,
    y="grupo_edad",
    hue="nacionalidad",
    order=eno_top_age["grupo_edad"].value_counts().index
)
plt.title(f"Distribución por grupo etario de {top_disease} - La Florida")
plt.xlabel("Cantidad")
plt.ylabel("Grupo de edad")
plt.show()

"""## Interpretación
Se identificó primero la enfermedad con mayor cantidadde notificaciones dentro de la base de datos filtrada para la comuna de La Florida, en donde pudimos obtener que la enfermedad más frecuente es VIH. A partir de eso, se construyó un subconjunto de datos que contiene solo los registros correspondientes a VIH, junto con los casos en donde la nacionalidad es conocida, es decir Chile/Extranjero. Teniendo esos datos, se elabroó un gráfico de barras para poder observar de mejor manera cómo se distribuyen los casos por grupo de edad y  por nacionalidad.

## Resultados
Podemos observar en el gráfico, que los casos de VIH se concentran principalmente en la población adulta-joven, en personas chilenas como extranjeras. También, podemos observar que el grupo etario con mayor notificaciones es entre 25-29 años. Por otro lado, en la población chilena, la distribución presenta una mayor cantidad de casos en prácticamente todos los grupos de edad, lo cual es consistente con su mayor peso poblacional dentro de la comuna. Sin embargo, la población ectranjera también se observa una presencia importante en los grupos entre 25-35 años lo que nos muestra que el patrón etario es bastante similar entre ambos grupos.
"""

eno_total = len(eno_com)
eno_chilean = (eno_com["nacionalidad"] == "Chile").sum()
eno_foreign = (eno_com["nacionalidad"] == "Extranjero").sum()
eno_desconocido = (eno_com["nacionalidad"] == "Desconocido").sum()
eno_top3 = ", ".join(eno_com["ENO"].value_counts().head(3).index.tolist())

pop_total = t1_summary.loc[0, "pop_total"]
eno_rate_per_10k = eno_total / pop_total * 10000

eno_summary = pd.DataFrame({
    "codigo_comuna": ["13110"],
    "nombre_comuna": ["La Florida"],
    "eno_total": [eno_total],
    "eno_chilean": [eno_chilean],
    "eno_foreign": [eno_foreign],
    "eno_desconocido": [eno_desconocido],
    "eno_top3_diseases": [eno_top3],
    "eno_rate_per_10k": [eno_rate_per_10k]
})

eno_summary

"""## Conclusión
Finalmente, se construyó una tabla resumen para la comuna de La Florida, integrando los principales indicadores obtenidos a partir de la base ENO.

Los resultados muestran que, en el período analizado, La Florida registra un total de 2.128 notificaciones. De ellas, 1.539 corresponden a personas de nacionalidad chilena, 342 a personas extranjeras y 247 a casos con nacionalidad*desconocida.

Además, las tres enfermedades más frecuentes en la comuna son VIH, Sífilis y Parotiditis, lo que confirma el patrón observado en los gráficos anteriores.

Por otra parte, al relacionar el total de notificaciones con la población comunal obtenida en la Tarea 1, se estimó una tasa bruta de 56,77 notificaciones por cada 10.000 habitantes.

###PARTE B
"""

grd_test_2022 = pd.read_csv(
    "GRD_PUBLICO_EXTERNO_2022.txt",
    sep="|",
    encoding="utf-16",
    low_memory=False,
    nrows=5
)

print(grd_test_2022.columns.tolist())
grd_test_2022.head()

grd_test_2023 = pd.read_csv(
    "GRD_PUBLICO_2023.txt",
    sep="|",
    encoding="utf-16",
    low_memory=False,
    nrows=5
)

print(grd_test_2023.columns.tolist())
grd_test_2023.head()

grd_test_2024 = pd.read_csv(
    "GRD_PUBLICO_2024.txt",
    sep="|",
    encoding="latin-1",
    low_memory=False,
    nrows=5
)

print(grd_test_2024.columns.tolist())
grd_test_2024.head()

grd_cols = [
    "COMUNA", "NACIONALIDAD", "SEXO", "FECHA_NACIMIENTO",
    "FECHA_INGRESO", "FECHAALTA", "TIPOALTA",
    "DIAGNOSTICO1", "DIAGNOSTICO2",
    "IR_29301_SEVERIDAD", "IR_29301_MORTALIDAD",
    "IR_29301_COD_GRD", "TIPO_INGRESO",
    "ESPECIALIDAD_MEDICA"
]

grd_2022 = pd.read_csv(
    "GRD_PUBLICO_EXTERNO_2022.txt",
    sep="|",
    encoding="utf-16",
    usecols=grd_cols,
    low_memory=False
)
grd_2022["year"] = 2022

grd_2023 = pd.read_csv(
    "GRD_PUBLICO_2023.txt",
    sep="|",
    encoding="utf-16",
    usecols=grd_cols,
    low_memory=False
)
grd_2023["year"] = 2023

grd_2024 = pd.read_csv(
    "GRD_PUBLICO_2024.txt",
    sep="|",
    encoding="latin-1",
    usecols=grd_cols,
    low_memory=False
)
grd_2024["year"] = 2024

grd = pd.concat([grd_2022, grd_2023, grd_2024], ignore_index=True)

print("Total de egresos cargados:", len(grd))
grd.head()

"""## Carga de datos GRD

Para la Parte B se cargaron los archivos GRD correspondientes a los años 2022, 2023 y 2024, seleccionando únicamente las variables necesarias para el análisis.

Durante este proceso fue necesario ajustar la lectura de los archivos, ya que no todos presentaban la misma codificación.

Una vez corregida la lectura, se agregó una variable `year` para identificar el año de origen de cada registro y luego se unieron las tres bases en una sola tabla consolidada.
"""

grd["COMUNA"] = grd["COMUNA"].astype(str).str.upper().str.strip()

grd_com = grd[grd["COMUNA"] == "LA FLORIDA"].copy()

print("Total egresos en La Florida:", len(grd_com))

grd_by_year = grd_com.groupby("year").size().reset_index(name="egresos")
grd_by_year

"""## Filtrado de egresos hospitalarios para La Florida

Una vez consolidada la base GRD de los años 2022, 2023 y 2024, se filtraron los registros correspondientes a la comuna de La Florida. Como resultado, se obtuvo un total de 37.559 egresos hospitalarios para el período analizado.

Al observar la distribución por año, se identifican 19.018 egresos en 2022, 17.516 en 2023 y 1.025 en 2024. En comparación con los dos años anteriores, el valor de 2024 es considerablemente menor, por lo que es probable que la base de ese año se encuentre incompleta o corresponda a un período parcial de registro.


"""

grd_com["fecha_ingreso_dt"] = pd.to_datetime(grd_com["FECHA_INGRESO"], errors="coerce")
grd_com["fecha_alta_dt"] = pd.to_datetime(grd_com["FECHAALTA"], errors="coerce")
grd_com["los"] = (grd_com["fecha_alta_dt"] - grd_com["fecha_ingreso_dt"]).dt.days

grd_com["los"].describe()

neg_los = (grd_com["los"] < 0).sum()
print("Filas con LOS negativo:", neg_los)

grd_com = grd_com[grd_com["los"] >= 0].copy()

"""## Cálculo de la estadía hospitalaria (Length of Stay)

A continuación, se calculó la variable los (*length of stay*), correspondiente a la duración de la hospitalización en días. Para ello, primero se transformaron las variables `FECHA_INGRESO` y `FECHAALTA` a formato de fecha y luego se calculó la diferencia entre ambas.

Los resultados muestran que se obtuvo información válida de estadía para **20.043 egresos hospitalarios** de la comuna de **La Florida**. La estadía promedio fue de **5,84 días**, mientras que la mediana fue de **2 días**, lo que sugiere que la mitad de las hospitalizaciones tuvo una duración igual o inferior a 2 días.

Además, se observa una alta dispersión en la distribución, con una desviación estándar de **13,82 días**. El valor mínimo fue de **0 días**, lo que indica la existencia de altas en el mismo día, mientras que el valor máximo alcanzó los **544 días**, reflejando la presencia de casos de hospitalización prolongada.

Por otra parte, no se detectaron registros con los negativo, por lo que no fue necesario eliminar observaciones por errores en el orden de las fechas. En consecuencia, todos los registros válidos de estadía pudieron mantenerse para el análisis posterior.
"""

grd_com["nat_group"] = grd_com["NACIONALIDAD"].apply(
    lambda x: "Chilean" if x == "CHILE" else "Foreign"
)

grd_com["nat_group"].value_counts().reset_index()